name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SQLX_OFFLINE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: add-clippy
      run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
    - name: clippy
      run: cargo clippy
    - name: Run tests account-state
      run: cargo test -p account-state --test account-state --verbose

